### ISSUE TITLE
Vue devtools is not installed by default

### ISSUE THREAD

**Issue by ashokgelal** [electron-userland/electrify#1] opened 2017-07-29 18:16 UTC
Looks like index.dev.ts doesn't get loaded at all and thus vue devtools doesn't get installed when doing `yarn run dev`. My electron-webpack fu is not strong enough to figure out why :)

**Comment by ashokgelal** [comment] 2017-07-29 19:19
Well, after further investigation it looks like index.dev.ts file do get loaded but to enable Vue devtools you have to set `Vue.config.devtools = true` in your `renderer/index.ts` file. Not sure why that is needed as you'd think that the tools would be enabled by default in dev mode.

**Comment by develar** [comment] 2017-07-30 07:08
Interesting, because `devtools: process.env.NODE_ENV !== 'production'` in the `vue.esm.js`

**Comment by develar** [comment] 2017-07-30 07:15
Yes, it is regression compared to original boilerplate, because of https://github.com/electron/electron/issues/3306

**Comment by develar** [comment] 2017-07-30 07:55
I will release fix today, thanks. Do yo want to contribute to this project or you use it as an example of electron-webpack vue project?

**Comment by ashokgelal** [comment] 2017-07-30 15:32
I'm actually using it as a boilerplate for a project. I started with electron-vue but ran into some problems. And I also wanted to use TypeScript. So this project was a good starting point. However, I had to strip out lot of things to make it work. I'd love to contribute but I'm not sure where you headed with this project. Some sort of milestones and some documentation on what it is supposed to do would need very helpful to contribute.

**Comment by develar** [comment] 2017-07-31 10:15
Because we recommend to use Vue and other project renderer dependencies as webpack DLL (to reduce build time),  `devtools: process.env.NODE_ENV !== 'production'` is compiled into `!1`.

Well, it is fixed in the webpack 0.7:

1. Remove main index.dev.ts — no need anymore. electron-webpack adds own file to install vue devtools extensions — no need to have this code in your project sources.
2. electron-webpack will use special file in a dev mode to automatically configure vue devtool, so, explicit `Vue.config.devtools ` is not required.

**Closed as completed** 2017-07-31 10:39 UTC
